### ISSUE TITLE
Manage functions as standalone files

### ISSUE THREAD

**Issue by Craigfis** [ThomWright/postgres-migrations#53] opened 2020-09-28 23:14 UTC
I'd like to be able to define my SQL functions in standalone files so that when I make changes to them they can be diffed against their previous versions. Currently I have to script dropping and recreating the function in a new migration, giving no easy way of seeing what the actual changes are via a diff.
If I could instead reference a function file in my migration I'd get the diff ability and the ability to have it automatically applied by the migration. (The hash for the migration should include hashing the contents of the referenced file.)

e.g. something like 
9_ChangeMyFunc.sql:
```
-- Apply updated version of function
!include ./funcs/my_function.sql

```
Where funcs/my_function.sql contains:
```
drop function my_function(IN param number);
create function my_function(IN param number, IN param2 text)
as $BODY$
  select param, param2
$BODY$;

```

**Comment by ThomWright** [comment] 2020-09-29 08:22
Hi, thanks for the issue. I think this is effectively a duplicate of #27, but with functions as a use case, not just views.

It's something I should consider supporting, I just haven't had the time/energy to put much thought into it.

**Closed by ThomWright** 2020-09-29 08:22 UTC

**Comment by Craigfis** [comment] 2020-09-29 16:59
So, @ThomWright, no thoughts on how you'd like to see this support implemented?
